/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/base/Avatar.vue')['default']
    Badge: typeof import('./src/components/base/Badge.vue')['default']
    Bubble: typeof import('./src/components/chat/messageCell/Bubble.vue')['default']
    'Bubble copy': typeof import('./src/components/chat/messageCell/Bubble copy.vue')['default']
    ChatConversationList: typeof import('./src/components/chat/ChatConversationList.vue')['default']
    ChatHeader: typeof import('./src/components/chat/ChatHeader.vue')['default']
    ChatInput: typeof import('./src/components/chat/ChatInput.vue')['default']
    ChatMessageList: typeof import('./src/components/chat/ChatMessageList.vue')['default']
    Checkbox: typeof import('./src/components/base/Checkbox.vue')['default']
    Contextmenu: typeof import('./src/components/base/Contextmenu.vue')['default']
    ConversationItem: typeof import('./src/components/chat/ConversationItem.vue')['default']
    copy: typeof import('./src/components/chat/messageCell/Bubble copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElMention: typeof import('element-plus/es')['ElMention']
    ElSplitter: typeof import('element-plus/es')['ElSplitter']
    ElSplitterPanel: typeof import('element-plus/es')['ElSplitterPanel']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconButton: typeof import('./src/components/base/IconButton.vue')['default']
    Index: typeof import('./src/components/chat/Index.vue')['default']
    MessageHead: typeof import('./src/components/chat/messageCell/MessageHead.vue')['default']
    MessageTrail: typeof import('./src/components/chat/messageCell/MessageTrail.vue')['default']
    ReplyMessage: typeof import('./src/components/chat/ReplyMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    System: typeof import('./src/components/chat/messageCell/System.vue')['default']
    TimeLine: typeof import('./src/components/chat/messageCell/TimeLine.vue')['default']
  }
}
