/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/base/Avatar.vue')['default']
    Badge: typeof import('./src/components/base/Badge.vue')['default']
    Bubble: typeof import('./src/components/chat/messageCell/Bubble.vue')['default']
    'Bubble copy': typeof import('./src/components/chat/messageCell/Bubble copy.vue')['default']
    ChatConversationList: typeof import('./src/components/chat/ChatConversationList.vue')['default']
    ChatHeader: typeof import('./src/components/chat/ChatHeader.vue')['default']
    ChatInput: typeof import('./src/components/chat/ChatInput.vue')['default']
    ChatMessageList: typeof import('./src/components/chat/ChatMessageList.vue')['default']
    Checkbox: typeof import('./src/components/base/Checkbox.vue')['default']
    Contextmenu: typeof import('./src/components/base/Contextmenu.vue')['default']
    ConversationItem: typeof import('./src/components/chat/ConversationItem.vue')['default']
    ConversationPicker: typeof import('./src/components/chat/conversationPicker/ConversationPicker.vue')['default']
    copy: typeof import('./src/components/chat/messageCell/TimeLine copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMention: typeof import('element-plus/es')['ElMention']
    ElSplitter: typeof import('element-plus/es')['ElSplitter']
    ElSplitterPanel: typeof import('element-plus/es')['ElSplitterPanel']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HistorySplit: typeof import('./src/components/chat/messageCell/HistorySplit.vue')['default']
    IconButton: typeof import('./src/components/base/IconButton.vue')['default']
    Index: typeof import('./src/components/chat/Index.vue')['default']
    Logo: typeof import('./src/components/ui/Logo.vue')['default']
    MergeForward: typeof import('./src/components/chat/messageCell/MergeForward.vue')['default']
    MessageFile: typeof import('./src/components/chat/messageCell/MessageFile.vue')['default']
    MessageHead: typeof import('./src/components/chat/messageCell/MessageHead.vue')['default']
    MessageImage: typeof import('./src/components/chat/messageCell/MessageImage.vue')['default']
    MessageListModal: typeof import('./src/components/chat/messageListModal/MessageListModal.vue')['default']
    MessageReply: typeof import('./src/components/chat/messageCell/MessageReply.vue')['default']
    MessageSmallVideo: typeof import('./src/components/chat/messageCell/MessageSmallVideo.vue')['default']
    MessageTrail: typeof import('./src/components/chat/messageCell/MessageTrail.vue')['default']
    ReplyMessage: typeof import('./src/components/chat/ReplyMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendFileDialog: typeof import('./src/components/chat/sendFileDialog/SendFileDialog.vue')['default']
    System: typeof import('./src/components/chat/messageCell/System.vue')['default']
    Tabs: typeof import('./src/components/base/Tabs.vue')['default']
    TimeLine: typeof import('./src/components/chat/messageCell/TimeLine.vue')['default']
  }
}
